FROM microsoft/dotnet:2.2-aspnetcore-runtime AS base
WORKDIR /app

ENV ASPNETCORE_URLS http://+:5000
EXPOSE 5000

FROM microsoft/dotnet:2.2-sdk AS build
WORKDIR /src

COPY ["NARE.API/azure-secrets.json", "/app/"]
COPY ["NARE.API/NARE.API.csproj", "NARE.API/"]
COPY ["NARE.Domain/NARE.Domain.csproj", "NARE.Domain/"]
COPY ["NARE.Infrastructure/NARE.Infrastructure.csproj", "NARE.Infrastructure/"]
COPY ["NARE.Application/NARE.Application.csproj", "NARE.Application/"]
COPY ["NARE.Persistence/NARE.Persistence.csproj", "NARE.Persistence/"]
RUN dotnet restore "NARE.API/NARE.API.csproj"
COPY . .
WORKDIR "/src/NARE.API"
RUN dotnet build "NARE.API.csproj" -c Release -o /app

FROM build AS publish
RUN dotnet publish "NARE.API.csproj" -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "NARE.API.dll"]